### ISSUE TITLE
Documentation seems inaccurate?

### ISSUE THREAD

**Issue by FGasper** [ecoAPM/xunit.ts#255]
Hello.

I’m trying to run the MyFirstTest example on the web page, but I’m getting this error every time:
```
> yarn xunit .out
yarn run v1.22.5
warning package.json: No license field
$ /root/temp/xunitts/node_modules/.bin/xunit .out
Starting xunit.ts...

An unhandled TypeError occurred: Class constructor TestSuite cannot be invoked without 'new'
TypeError: Class constructor TestSuite cannot be invoked without 'new'
    at new MyTestSuite (/root/temp/xunitts/.out/MyTestSuite.js:62:42)
    at Function.<anonymous> (/root/temp/xunitts/node_modules/xunit.ts/dist/src/Runners/TestSuiteLoader.js:52:27)
    at Generator.next (<anonymous>)
    at fulfilled (/root/temp/xunitts/node_modules/xunit.ts/dist/src/Runners/Testerror Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Is there something I’m missing?

Thank you in advance!

**Comment by SteveDesmond-ca** [comment]
Fixed in 49c3f38
